name: Python CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m venv .venv
          . .venv/bin/activate
          python -m pip install --upgrade pip
          pip install flake8 pytest

      # Lint the code with Flake8
      - name: Run Flake8
        run: |
          . .venv/bin/activate
          python -m flake8 calculator.py test_calculator.py

      # Run the tests with Pytest
      - name: Run tests
        run: |
          . .venv/bin/activate
          python -m pytest --cov=calculator --cov-fail-under=50
